/**
 * `?api=mock`: a PrimersClient that replays design fixtures (real Primer3
 * 2.6.1 output on sorghum_bicolor, generated by
 * test/components/fixtures/build-designs.mjs) and simulates check jobs
 * (queued → running with partial results → done). Check results are
 * synthetic, except the P2/P3 off-targets and the J_L + P1_R transcriptome
 * groups, which follow the spec examples.
 */
import {
  CHECK_DEFAULTS,
  cdnaToGenomicBlocks,
  hashString,
  pairKey,
  PANGENOME_TRANSCRIPT_MODELS_ONLY,
  pollCheckJob,
  PrimersApiError,
  revcomp,
  summarizePangenome,
  transcriptLayout,
  type CheckJob,
  type CheckRequest,
  type CheckResults,
  type DesignRequest,
  type DesignResponse,
  type GenomeEntry,
  type GenomesResponse,
  type GrameneGene,
  type OffTarget,
  type PangenomeGenomeResult,
  type PangenomeStatus,
  type PollOptions,
  type PrimerOligo,
  type PrimerPair,
  type PrimersClient,
  type RequestOptions,
  type SpecificityPairResult,
  type TranscriptomePairResult,
} from 'gramene-primers';
import gene200Json from '../../test/fixtures/genes/SORBI_3001G000200.json';
import gene700Json from '../../test/fixtures/genes/SORBI_3001G000700.json';
import gene46200Json from '../../test/fixtures/genes/SORBI_3001G046200.json';
import gene87700Json from '../../test/fixtures/genes/SORBI_3004G087700.json';
import gene87700Seq from '../../test/fixtures/sequences/SORBI_3004G087700.gene.txt?raw';
import gene200Design from '../../test/components/fixtures/designs/gene-SORBI_3001G000200-flanks.json';
import gene700Design from '../../test/components/fixtures/designs/gene-SORBI_3001G000700.json';
import noPairsDesign from '../../test/components/fixtures/designs/no-pairs-SORBI_3001G000200.json';
import regionDesign from '../../test/components/fixtures/designs/region-1-11080-15099-minus.json';
import sequenceDesign from '../../test/components/fixtures/designs/sequence-iupac.json';
import tx200Design from '../../test/components/fixtures/designs/transcript-SORBI_3001G000200.json';
import tx46200a from '../../test/components/fixtures/designs/transcript-SORBI_3001G046200.1.json';
import tx46200b from '../../test/components/fixtures/designs/transcript-SORBI_3001G046200.2.json';
import tx87700Design from '../../test/components/fixtures/designs/transcript-SORBI_3004G087700.3.json';
import type { MockVariant } from './pages';

export const GENES: Readonly<Record<string, GrameneGene>> = Object.freeze({
  SORBI_3001G000200: gene200Json as unknown as GrameneGene,
  SORBI_3001G000700: gene700Json as unknown as GrameneGene,
  SORBI_3001G046200: gene46200Json as unknown as GrameneGene,
  SORBI_3004G087700: gene87700Json as unknown as GrameneGene,
});

export const SEQS = Object.freeze({
  P1_L: 'GATCGACAATCCGACGATAGAAG',
  P1_R: 'GTGAACATCATGCTGCCCGATG',
  P2_L: 'GGACAGCTCCACAACATATCAG',
  P2_R: 'GGACATTTGAAGCCCATGGCC',
  P3_L: 'GATATCAGTGGAATCATAAGACCG',
  P3_R: 'CATCGATATCAGGATCTGGCTT',
  P5_L: 'CGACGAGGAGGCGCTGCGATG',
  J_L: 'CCAACAAAGTCATGGATGCACT',
});

export interface MockClientOptions {
  variant?: MockVariant;
  /** Multiplies every simulated latency (tests use a small value). */
  delayScale?: number;
  /** Simulate an API error code on the first design or check request. */
  failWith?: string | null;
  /** Skip the queued phase of check jobs. */
  skipQueue?: boolean;
}

const clone = <T,>(v: T): T => JSON.parse(JSON.stringify(v)) as T;

function abortError(): Error {
  return new DOMException('The operation was aborted.', 'AbortError');
}

function wait(ms: number, signal?: AbortSignal): Promise<void> {
  return new Promise((resolve, reject) => {
    if (signal?.aborted) return reject(abortError());
    const t = setTimeout(() => {
      signal?.removeEventListener('abort', onAbort);
      resolve();
    }, ms);
    const onAbort = () => {
      clearTimeout(t);
      reject(abortError());
    };
    signal?.addEventListener('abort', onAbort, { once: true });
  });
}

function gc(seq: string): number {
  return Math.round(((seq.match(/[GC]/g)?.length ?? 0) / seq.length) * 10000) / 100;
}

/** Rough salt-adjusted Tm, for mock pairs only. */
function roughTm(seq: string): number {
  const g = (seq.match(/[GC]/g)?.length ?? 0);
  return Math.round((64.9 + (41 * (g - 16.4)) / seq.length) * 100) / 100;
}

function oligo(seq: string, start: number, end: number, extra: Partial<PrimerOligo> = {}): PrimerOligo {
  return { seq, start, end, len: seq.length, tm: roughTm(seq), gc: gc(seq), self_any_th: 0, self_end_th: 0, hairpin_th: 0, end_stability: 3.5, penalty: 0.4, junction: null, genomic: null, ...extra };
}

/** Gene-mode template on SORBI_3004G087700 (+, flanks 0) with the spec P1/P2/P3 pairs. */
function verifiedGenePairsDesign(): DesignResponse {
  const gene = GENES.SORBI_3004G087700!;
  const seq = gene87700Seq.trim();
  const g0 = gene.location.start;
  const pair = (rank: number, left: string, right: string, gStart: number, gEnd: number): PrimerPair => {
    const ls = gStart - g0 + 1;
    const re = gEnd - g0 + 1;
    const rs = re - right.length + 1;
    return {
      rank,
      penalty: 0.3 + rank / 10,
      product_size: re - ls + 1,
      product_tm: 82.5,
      compl_any_th: 0,
      compl_end_th: 0,
      left: oligo(left, ls, ls + left.length - 1, { genomic: { region: '4', start: gStart, end: gStart + left.length - 1, strand: 1, blocks: [{ start: gStart, end: gStart + left.length - 1 }] } }),
      right: oligo(right, rs, re, { genomic: { region: '4', start: gEnd - right.length + 1, end: gEnd, strand: -1, blocks: [{ start: gEnd - right.length + 1, end: gEnd }] } }),
      product: { start: ls, end: re, genomic: { region: '4', start: gStart, end: gEnd, strand: 1 } },
    };
  };
  const layout = transcriptLayout(gene, 'SORBI_3004G087700.3')!;
  return {
    template: {
      mode: 'gene',
      system_name: 'sorghum_bicolor',
      gene_id: gene._id,
      transcript_id: layout.transcriptId,
      region: '4',
      start: gene.location.start,
      end: gene.location.end,
      strand: 1,
      length: seq.length,
      seq,
      masked: false,
      mask_source: null,
      mask: [],
      masked_fraction: 0,
      features: {
        gene: { start: 1, end: seq.length },
        exons: layout.segments.map((s) => ({ id: s.exonId, start: s.gStart - g0 + 1, end: s.gEnd - g0 + 1, genomic: { start: s.gStart, end: s.gEnd } })),
        cds: null,
        junctions: [],
      },
    },
    pairs: [pair(0, SEQS.P1_L, SEQS.P1_R, 7422190, 7422843), pair(1, SEQS.P2_L, SEQS.P2_R, 7423537, 7423746), pair(2, SEQS.P3_L, SEQS.P3_R, 7422482, 7423061)],
    explain: { left: { raw: 'mock', considered: 3, ok: 3 }, right: { raw: 'mock', considered: 3, ok: 3 }, pair: { raw: 'mock', considered: 3, ok: 3 } },
    settings: { preset: 'pcr', junction_spanning: false, avoid_repeats: false, repeat_mask_mode: null, params: {} },
    engine: { primer3: '2.6.1 (mock replay)' },
    warnings: [],
  };
}

/** Transcript-mode design on SORBI_3004G087700.3 with J_L (spans junction 743) + P1_R, 278 bp. */
function verifiedQpcrDesign(): DesignResponse {
  const gene = GENES.SORBI_3004G087700!;
  const layout = transcriptLayout(gene, 'SORBI_3004G087700.3')!;
  const lb = cdnaToGenomicBlocks(layout, 730, 751);
  const rb = cdnaToGenomicBlocks(layout, 986, 1007);
  const env = (b: { start: number; end: number }[]) => ({ start: b[0]!.start, end: b[b.length - 1]!.end });
  const all = [...lb, ...rb].sort((a, b) => a.start - b.start);
  const product = env(all);
  const res = clone(tx87700Design.response) as unknown as DesignResponse;
  res.pairs = [
    {
      rank: 0,
      penalty: 0.52,
      product_size: 278,
      product_tm: 83.1,
      compl_any_th: 0,
      compl_end_th: 0,
      left: oligo(SEQS.J_L, 730, 751, { junction: { position: 743, overlap_5p: 14, overlap_3p: 8 }, genomic: { region: '4', ...env(lb), strand: 1, blocks: lb } }),
      right: oligo(SEQS.P1_R, 986, 1007, { genomic: { region: '4', ...env(rb), strand: -1, blocks: rb } }),
      product: { start: 730, end: 1007, genomic: { region: '4', ...product, strand: 1 }, genomic_size: product.end - product.start + 1 },
    },
  ];
  res.engine = { primer3: '2.6.1 (mock replay)' };
  return res;
}

/** Sequence-mode design: P5_L + 180 nt of SORBI_3004G087700 + reverse complement of P2_R. */
function repetitiveP5lDesign(): DesignResponse {
  const middle = gene87700Seq.trim().slice(3000, 3180);
  const seq = `${SEQS.P5_L}${middle}${revcomp(SEQS.P2_R)}`;
  const end = seq.length;
  return {
    template: { mode: 'sequence', system_name: 'sorghum_bicolor', gene_id: null, transcript_id: null, region: null, start: null, end: null, strand: null, length: end, seq, masked: false, mask_source: null, mask: [], masked_fraction: 0, features: {} },
    pairs: [
      {
        rank: 0,
        penalty: 1.2,
        product_size: end,
        product_tm: null,
        compl_any_th: 0,
        compl_end_th: 0,
        left: oligo(SEQS.P5_L, 1, SEQS.P5_L.length),
        right: oligo(SEQS.P2_R, end - SEQS.P2_R.length + 1, end),
        product: { start: 1, end, genomic: null },
      },
    ],
    explain: null,
    settings: { preset: 'pcr', junction_spanning: false, avoid_repeats: false, repeat_mask_mode: null, params: {} },
    engine: { primer3: '2.6.1 (mock replay)' },
    warnings: [],
  };
}

function fixtureFor(req: DesignRequest, variant: MockVariant): DesignResponse | PrimersApiError {
  const pick = (f: { response: unknown }) => clone(f.response) as DesignResponse;
  if (variant === 'verified-gene-pairs' && req.mode === 'gene') return verifiedGenePairsDesign();
  if (variant === 'verified-qpcr-pair' && req.mode === 'transcript') return verifiedQpcrDesign();
  if (variant === 'repetitive-p5l' && req.mode === 'sequence') return repetitiveP5lDesign();
  switch (req.mode) {
    case 'gene':
      if (req.gene_id === 'SORBI_3001G000200') return pick(gene200Design);
      if (req.gene_id === 'SORBI_3001G000700') return pick(gene700Design);
      if (req.gene_id === 'SORBI_3004G087700') return verifiedGenePairsDesign();
      break;
    case 'transcript': {
      const ranges = req.params?.product_size_ranges;
      if (req.gene_id === 'SORBI_3001G000200') return ranges && ranges.every((r) => r[1] < 80) ? pick(noPairsDesign) : pick(tx200Design);
      if (req.gene_id === 'SORBI_3001G046200') return req.transcript_id === 'SORBI_3001G046200.1' ? pick(tx46200a) : pick(tx46200b);
      if (req.gene_id === 'SORBI_3004G087700') return pick(tx87700Design);
      break;
    }
    case 'region':
      return pick(regionDesign);
    case 'sequence':
      return pick(sequenceDesign);
  }
  return new PrimersApiError({ status: 404, code: 'UNKNOWN_GENE', message: `The mock API has no fixture for ${req.gene_id ?? req.mode}` });
}

/** Adds an illustrative repeat mask when `avoid_repeats` is set. */
function applyMockMask(res: DesignResponse, req: DesignRequest): DesignResponse {
  if (!req.avoid_repeats) return res;
  const L = res.template.length;
  const runs: [number, number][] = [];
  for (let s = Math.floor(L * 0.12); s < L; s += Math.floor(L * 0.27)) runs.push([s, Math.max(20, Math.floor(L * 0.06))]);
  const source = res.template.mode === 'sequence' ? 'user_lowercase' : res.template.system_name === 'sorghum_rio' ? 'softmask' : 'blast_depth';
  res.template = { ...res.template, masked: true, mask_source: source, mask: runs, masked_fraction: runs.reduce((a, r) => a + r[1], 0) / L };
  if (source === 'blast_depth') res.warnings = [...res.warnings, { code: 'BLAST_DEPTH_MASK', message: 'Repeats estimated by BLAST copy number (mock); multi-copy gene families are masked too' }];
  return res;
}

const GENOME_NAMES: ReadonlyArray<[string, string, Partial<GenomeEntry>]> = [
  ['sorghum_bicolor', 'Sb BTx623 v3', { repeat_masking: 'unmasked_copy', total_bases: 708735318, map_id: 'GCA_000003195.3' }],
  ['sorghum_353', 'Sb verticilliflorum 353', {}],
  ['sorghum_grassl', 'Sb Grassl', { has_cdna_blastdb: false }],
  ['sorghum_leoti', 'Sb Leoti', {}],
  ['sorghum_rio', 'Sb Rio', { repeat_masking: 'soft_masked' }],
  ['sorghum_tx436pac', 'Sb Tx436 (PacBio)', { repeat_masking: 'soft_masked' }],
  ['sorghum_tx2783pac', 'Sb Tx2783 (PacBio)', { repeat_masking: 'soft_masked' }],
  ['sorghum_is929', 'Sb IS929', {}],
  ['sorghum_pi534133', 'Sb PI534133', {}],
  ['sorghum_btx642', 'Sb BTx642', { has_blastdb: false, has_cdna_blastdb: false, total_bases: null }],
];

export function mockGenomes(systemName: string): GenomesResponse {
  const genomes: GenomeEntry[] = GENOME_NAMES.map(([system_name, display_name, extra], i) => ({
    system_name,
    display_name,
    taxon_id: 4558000 + i,
    map_id: `GCA_mock_${i}`,
    is_query: system_name === systemName,
    has_sequence: true,
    has_blastdb: true,
    has_cdna_blastdb: true,
    repeat_masking: 'unmasked_copy',
    total_bases: 690_000_000 + i * 7_000_000,
    warnings: [],
    ...extra,
  }));
  genomes.sort((a, b) => Number(b.is_query) - Number(a.is_query) || a.display_name.localeCompare(b.display_name));
  return {
    system_name: systemName,
    species: { taxon_id: 4558, name: 'Sorghum bicolor' },
    counts: { total: genomes.length, with_blastdb: genomes.filter((g) => g.has_blastdb).length, with_cdna_blastdb: genomes.filter((g) => g.has_cdna_blastdb).length },
    genomes,
  };
}

/** Deterministic 0–1 random numbers per string. */
function rng(seed: string): () => number {
  let s = parseInt(hashString(seed), 16) || 1;
  return () => {
    s = (s + 0x6d2b79f5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function amp(region: string, start: number, size: number, extra: Partial<OffTarget> = {}): OffTarget {
  return { region, start, end: start + size - 1, size, orientation: 'LR', likelihood: 'likely', left_mm: 0, right_mm: 0, left_3p_mm: 0, right_3p_mm: 0, left_mm_pos: [], right_mm_pos: [], approx: false, genes: [], ...extra };
}

interface StoredJob {
  id: string;
  request: CheckRequest;
  createdAt: number;
  sizes: Map<string, number>;
}

export class MockPrimersClient implements PrimersClient {
  readonly apiBase = 'mock://sorghum_v11';
  private readonly jobs = new Map<string, StoredJob>();
  private readonly productSizes = new Map<string, number>();
  private failWith: string | null;

  constructor(private readonly options: MockClientOptions = {}) {
    this.failWith = options.failWith ?? null;
  }

  private delay(ms: number, signal?: AbortSignal): Promise<void> {
    return wait(ms * (this.options.delayScale ?? 1), signal);
  }

  private takeFailure(kind: 'design' | 'check'): PrimersApiError | null {
    const code = this.failWith;
    if (!code) return null;
    const designCodes = ['BUSY', 'VALIDATION', 'FEATURE_DISABLED', 'PRIMER3_UNAVAILABLE'];
    if ((kind === 'design') !== designCodes.includes(code)) return null;
    this.failWith = null;
    switch (code) {
      case 'BUSY':
        return new PrimersApiError({ status: 503, code, message: 'Too many design requests', details: { retry_after_s: 3 }, retryAfterMs: 3000 });
      case 'VALIDATION':
        return new PrimersApiError({ status: 400, code, message: 'Validation errors', errors: [{ code: 'OBJECT_ADDITIONAL_PROPERTIES', message: 'Additional properties not allowed: mock', path: ['mock'] }] });
      case 'QUEUE_FULL':
        return new PrimersApiError({ status: 503, code, message: 'The check queue is full', details: { retry_after_s: 10 }, retryAfterMs: 10000 });
      case 'JOB_TOO_LARGE':
        return new PrimersApiError({ status: 422, code, message: 'Estimated CPU time exceeds the limit', details: { estimate_cpu_s: 7250, limit: 6000 } });
      default:
        return new PrimersApiError({ status: 503, code, message: `${code} (mock)` });
    }
  }

  async design(req: DesignRequest, o?: RequestOptions): Promise<DesignResponse> {
    await this.delay(450, o?.signal);
    const failure = this.takeFailure('design');
    if (failure) throw failure;
    const res = fixtureFor(req, this.options.variant ?? 'default');
    if (res instanceof PrimersApiError) throw res;
    for (const p of res.pairs) this.productSizes.set(pairKey(p.left.seq, p.right.seq), p.product_size);
    const out = applyMockMask(res, req);
    if (req.template_only) return { ...out, pairs: [], explain: null };
    return out;
  }

  async submitCheck(req: CheckRequest, o?: RequestOptions): Promise<CheckJob & { created: boolean }> {
    await this.delay(250, o?.signal);
    const failure = this.takeFailure('check');
    if (failure) throw failure;
    const id = [0, 1, 2, 3].map((i) => hashString(`${i}:${JSON.stringify(req)}`)).join('');
    const existing = this.jobs.get(id);
    if (!existing) {
      const sizes = new Map<string, number>();
      for (const p of req.pairs) sizes.set(p.id, p.expected ? p.expected.end - p.expected.start + 1 : this.productSizes.get(pairKey(p.left, p.right)) ?? 200);
      this.jobs.set(id, { id, request: clone(req), createdAt: Date.now(), sizes });
    }
    return { ...this.snapshot(this.jobs.get(id)!), created: !existing };
  }

  async getCheck(jobId: string, o?: RequestOptions): Promise<CheckJob> {
    await this.delay(120, o?.signal);
    const job = this.jobs.get(jobId);
    if (!job) throw new PrimersApiError({ status: 404, code: 'UNKNOWN_JOB', message: 'Unknown or expired job' });
    return this.snapshot(job);
  }

  pollCheck(jobId: string, o?: PollOptions): Promise<CheckJob> {
    return pollCheckJob(this, jobId, o);
  }

  async runCheck(req: CheckRequest, o?: Omit<PollOptions, 'resubmit' | 'initialJob'>): Promise<CheckJob> {
    const job = await this.submitCheck(req, { signal: o?.signal });
    o?.onUpdate?.(job);
    if (job.status === 'done' || job.status === 'error') return job;
    return pollCheckJob(this, job.job_id, { ...o, resubmit: req, initialJob: job });
  }

  async listGenomes(systemName: string, o?: RequestOptions): Promise<GenomesResponse> {
    await this.delay(150, o?.signal);
    return mockGenomes(systemName);
  }

  async getGene(geneId: string, o?: RequestOptions): Promise<GrameneGene | null> {
    await this.delay(100, o?.signal);
    return GENES[geneId] ? clone(GENES[geneId]!) : null;
  }

  /** The job as the server would report it now. */
  private snapshot(job: StoredJob): CheckJob {
    const req = job.request;
    const scale = this.options.delayScale ?? 1;
    const pangenome = !!req.checks?.includes('pangenome');
    const mode = req.mode ?? 'region';
    const genomes = pangenome
      ? req.genomes ?? mockGenomes(req.system_name).genomes.filter((g) => !g.is_query && (mode === 'transcript' ? g.has_cdna_blastdb : g.has_blastdb)).map((g) => g.system_name)
      : [];
    const queuedMs = this.options.skipQueue ? 0 : 1500 * scale;
    const runMs = (pangenome ? 7000 : 2500) * scale;
    const elapsed = Date.now() - job.createdAt;
    const total = 1 + (mode === 'transcript' ? 1 : 0) + genomes.length;
    const normalized: CheckRequest = { ...req, mode, checks: pangenome ? ['pangenome', 'specificity'] : ['specificity'], genomes: pangenome ? [...genomes].sort() : undefined, pairs: req.pairs.map((p) => ({ ...p, left: p.left.toUpperCase(), right: p.right.toUpperCase() })) };
    const base: CheckJob = {
      job_id: job.id,
      status: 'queued',
      kind: pangenome ? 'pangenome' : 'specificity',
      queue_position: 0,
      progress: { done: 0, total, stage: 'queued', running: [] },
      estimate: { cpu_s: 16 },
      created_at: new Date(job.createdAt).toISOString(),
      request: normalized,
      warnings: [],
      results: null,
    };
    if (elapsed < queuedMs) return base;
    const fraction = Math.min(1, (elapsed - queuedMs) / runMs);
    const done = Math.floor(fraction * total);
    const results = this.results(job, genomes, fraction);
    if (fraction >= 1) {
      return { ...base, status: 'done', partial: false, queue_position: null, progress: { done: total, total, stage: 'done', running: [] }, started_at: base.created_at, finished_at: new Date().toISOString(), results, warnings: results.warnings ?? [] };
    }
    const stage = done === 0 ? 'reference' : done === 1 && mode === 'transcript' ? 'transcriptome' : 'pangenome';
    const running = stage === 'pangenome' ? genomes.slice(Math.max(0, done - (mode === 'transcript' ? 2 : 1)), Math.max(0, done - (mode === 'transcript' ? 2 : 1)) + 2) : [];
    return { ...base, status: 'running', partial: true, queue_position: null, progress: { done, total, stage, running }, started_at: base.created_at, results };
  }

  private results(job: StoredJob, genomes: string[], fraction: number): CheckResults {
    const req = job.request;
    const mode = req.mode ?? 'region';
    const pairs = req.pairs;
    const specDone = fraction > 0.1;
    const txDone = mode === 'transcript' && fraction > 0.2;
    const panCount = Math.floor(Math.max(0, fraction - 0.2) / 0.8 * genomes.length);
    const primers: CheckResults['primers'] = {};
    for (const p of pairs) {
      for (const seq of [p.left.toUpperCase(), p.right.toUpperCase()]) {
        const sites = seq === SEQS.P5_L ? 14 : 1 + Math.floor(rng(seq)() * 2);
        primers[seq] = { len: seq.length, near_perfect_sites: sites, repetitive: sites > 5, truncated: false, sensitivity: { reference: { word_size: 5, guaranteed_max_mismatches: seq.length >= 22 ? 3 : 2 }, pangenome: { word_size: 6, guaranteed_max_mismatches: 2 } } };
      }
    }
    const specificity = specDone
      ? { target: 'genome' as const, pairs: pairs.map((p): SpecificityPairResult => this.specificityFor(p, mode, job.sizes.get(p.id) ?? 200)) }
      : null;
    const transcriptome = txDone ? { target: 'cdna' as const, pairs: pairs.map((p): TranscriptomePairResult => this.transcriptomeFor(p, req, job.sizes.get(p.id) ?? 200)) } : null;
    const warnings = mode === 'transcript' && req.checks?.includes('pangenome') ? [{ code: PANGENOME_TRANSCRIPT_MODELS_ONLY, message: 'Transcript-mode pan-genome searches annotated transcript models only (mock)' }] : [];
    const pangenome = req.checks?.includes('pangenome')
      ? {
          target: mode === 'transcript' ? ('cdna' as const) : ('genome' as const),
          pairs: pairs.map((p) => {
            const size = job.sizes.get(p.id) ?? 200;
            const rows = genomes.slice(0, panCount).map((g) => this.pangenomeCell(p, g, size, mode));
            return { id: p.id, reference_size: size, summary: summarizePangenome(rows), genomes: rows };
          }),
        }
      : null;
    return {
      engine: { algorithm_version: '2', blast: '2.13.0 (mock)', reference: 'blastn-short r1 p-1 ws5 ungapped', pangenome: 'blastn-short r1 p-1 ws6 ungapped' },
      params: { ...CHECK_DEFAULTS, ...req.params },
      reference: { system_name: req.system_name, map_id: 'GCA_000003195.3', total_bases: 708735318 },
      sensitivity_note: 'Mock results. Sites are detected only if they contain an exact match of at least the word size; mid-primer indels in short primers may be missed.',
      primers,
      specificity,
      transcriptome,
      pangenome,
      warnings,
      timings_ms: { reference: 11000 },
    };
  }

  private specificityFor(p: CheckRequest['pairs'][number], mode: string, size: number): SpecificityPairResult {
    const key = pairKey(p.left, p.right);
    const onTarget = p.expected ? amp(p.expected.region, p.expected.start, p.expected.end - p.expected.start + 1, { genes: [{ id: 'SORBI_3004G087700', strand: 1 }] }) : null;
    if (key === pairKey(SEQS.P2_L, SEQS.P2_R)) {
      return {
        id: p.id,
        verdict: 'off_targets',
        on_target_inferred: false,
        truncated: false,
        on_target: onTarget,
        off_target_count: 2,
        unlikely_count: 0,
        off_targets: [
          amp('4', 7437317, 210, { genes: [{ id: 'SORBI_3004G087800', strand: 1 }] }),
          amp('5', 66890615, 210, { orientation: 'RL', left_mm: 2, right_mm: 2, left_mm_pos: [10, 7], right_mm_pos: [15, 10], genes: [{ id: 'SORBI_3005G183900', strand: -1 }] }),
        ],
        gdna_products: [],
      };
    }
    if (key === pairKey(SEQS.P3_L, SEQS.P3_R)) {
      return {
        id: p.id,
        verdict: 'off_targets',
        on_target: onTarget,
        off_target_count: 1,
        off_targets: [amp('4', 7436221, 625, { likelihood: 'likely_weak', left_mm: 1, left_3p_mm: 1, left_mm_pos: [1], genes: [{ id: 'SORBI_3004G087800', strand: 1 }] })],
        gdna_products: [],
      };
    }
    if (mode === 'transcript') {
      return { id: p.id, verdict: 'specific', on_target: null, off_target_count: 0, off_targets: [], gdna_products: [amp('4', 7422822, Math.round(size * 1.7))] };
    }
    if (!p.expected) {
      return { id: p.id, verdict: 'specific', on_target_inferred: true, on_target: amp('4', 7425000, size), off_target_count: 0, off_targets: [], gdna_products: [] };
    }
    return { id: p.id, verdict: 'specific', on_target_inferred: false, on_target: onTarget, off_target_count: 0, unlikely_count: 1, off_targets: [], gdna_products: [] };
  }

  private transcriptomeFor(p: CheckRequest['pairs'][number], req: CheckRequest, size: number): TranscriptomePairResult {
    const geneId = req.gene_id ?? 'SORBI_3004G087700';
    const isoforms = (GENES[geneId]?.gene_structure?.transcripts ?? []).map((t, i) => ({ transcript_id: t.id, start: 100 + i * 50, end: 99 + i * 50 + size, size }));
    const onTarget = { gene_id: geneId, isoforms, size_min: size, size_max: size, likelihood: 'likely' as const, orientation: 'LR' as const, left_mm: 0, right_mm: 0, left_3p_mm: 0, right_3p_mm: 0, left_mm_pos: [], right_mm_pos: [], approx: false };
    if (pairKey(p.left, p.right) !== pairKey(SEQS.J_L, SEQS.P1_R)) return { id: p.id, verdict: 'specific', on_target: onTarget, off_target_count: 0, off_targets: [] };
    return {
      id: p.id,
      verdict: 'off_targets',
      on_target: onTarget,
      off_target_count: 2,
      off_targets: [
        { gene_id: 'SORBI_3005G183900', isoforms: [{ transcript_id: 'SORBI_3005G183900.1', start: 100, end: 390, size: 291 }], size_min: 291, size_max: 291, likelihood: 'likely', orientation: 'LR', left_mm: 2, right_mm: 2, left_3p_mm: 0, right_3p_mm: 0, left_mm_pos: [10, 7], right_mm_pos: [15, 10], approx: false },
        { gene_id: 'SORBI_3004G087800', isoforms: [{ transcript_id: 'SORBI_3004G087800.1', start: 50, end: 330, size: 281 }], size_min: 281, size_max: 281, likelihood: 'likely_weak', orientation: 'LR', left_mm: 1, right_mm: 0, left_3p_mm: 1, right_3p_mm: 0, left_mm_pos: [1], right_mm_pos: [], approx: true },
      ],
    };
  }

  private pangenomeCell(p: CheckRequest['pairs'][number], systemName: string, size: number, mode: string): PangenomeGenomeResult {
    const entry = mockGenomes('sorghum_bicolor').genomes.find((g) => g.system_name === systemName);
    const display = entry?.display_name ?? systemName;
    const hasDb = mode === 'transcript' ? entry?.has_cdna_blastdb !== false : entry?.has_blastdb !== false;
    if (!hasDb) return { system_name: systemName, display_name: display, status: 'db_unavailable', primary: null, other_amplicons: 0, others: [], nearest: null };
    const r = rng(`${pairKey(p.left, p.right)}|${systemName}`)();
    const status: PangenomeStatus = r < 0.6 ? 'single_perfect' : r < 0.8 ? 'single_mismatch' : r < 0.9 ? 'multiple' : 'no_amplicon';
    const delta = status === 'single_perfect' ? 0 : Math.round((r * 100) % 7) - 3;
    const primary =
      status === 'no_amplicon'
        ? null
        : {
            region: '4',
            start: 7400000 + Math.round(r * 90000),
            end: 7400000 + Math.round(r * 90000) + size + delta - 1,
            strand: 1 as const,
            size: size + delta,
            size_delta: delta,
            orientation: 'LR' as const,
            likelihood: status === 'single_mismatch' && r > 0.72 ? ('likely_weak' as const) : ('likely' as const),
            left_mm: status === 'single_mismatch' ? 1 : 0,
            right_mm: 0,
            left_3p_mm: status === 'single_mismatch' && r > 0.72 ? 1 : 0,
            right_3p_mm: 0,
            left_mm_pos: status === 'single_mismatch' ? [r > 0.72 ? 1 : 12] : [],
            right_mm_pos: [],
            mismatch_in_3p_window: status === 'single_mismatch' && r > 0.72,
            terminal_mismatch: status === 'single_mismatch' && r > 0.76,
            genes: [{ id: `${systemName.replace('sorghum_', '')}.004G093400` }],
            ortholog: true,
          };
    return {
      system_name: systemName,
      display_name: display,
      status,
      ortholog_annotated: status === 'no_amplicon' ? r > 0.95 : true,
      primary,
      other_amplicons: status === 'multiple' ? 1 : 0,
      others: status === 'multiple' && primary ? [{ ...primary, start: primary.start + 50000, end: primary.end + 50000, ortholog: false }] : [],
      nearest: null,
    };
  }
}

export function createMockClient(options: MockClientOptions = {}): MockPrimersClient {
  return new MockPrimersClient(options);
}
