import { readFileSync } from 'node:fs';
import type { CheckJob, DesignRequest, DesignResponse } from '../../src/types';
import { doneCheckJob, qpcrCheckPair } from '../fixtures/samples';
import { pkgPath } from '../paths';

export const API = 'http://fake.test/sorghum_v11';

export interface DesignFixture {
  request: DesignRequest;
  response: DesignResponse;
}

/** Real Primer3 designs generated by test/components/fixtures/build-designs.mjs. */
export function designFixture(name: string): DesignFixture {
  return JSON.parse(readFileSync(pkgPath('test', 'components', 'fixtures', 'designs', `${name}.json`), 'utf8')) as DesignFixture;
}

export function deepFreeze<T>(value: T): T {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const v of Object.values(value as Record<string, unknown>)) deepFreeze(v);
  }
  return value;
}

export const JOB_ID = doneCheckJob().job_id;

/** POST /primers/check 202 answer (spec §A.2.3). */
export function queuedJob(): CheckJob & { created: boolean } {
  return {
    job_id: JOB_ID,
    status: 'queued',
    kind: 'pangenome',
    queue_position: 1,
    progress: { done: 0, total: 5, stage: 'queued', running: [] },
    estimate: { cpu_s: 34 },
    created_at: '2026-09-12T20:01:02.000Z',
    warnings: [],
    created: true,
  };
}

/**
 * The POST /primers/check 200 answer for an existing job: its status and progress only, never
 * `results`, `request` or `error` (gramene-swagger jobs/index.js submit()).
 */
export function submitAnswer(job: CheckJob, created = false): CheckJob & { created: boolean } {
  return {
    job_id: job.job_id,
    status: job.status,
    kind: job.kind,
    queue_position: job.status === 'queued' ? job.queue_position ?? 0 : null,
    progress: job.progress,
    estimate: job.estimate ?? { cpu_s: 35 },
    created_at: job.created_at ?? '2026-09-12T20:01:02.000Z',
    warnings: job.warnings ?? [],
    created,
  };
}

/** The P2/P3 job while running: P2 specificity and one pan-genome genome are in. */
export function runningPartialJob(): CheckJob {
  const done = doneCheckJob();
  const results = done.results!;
  const p2 = results.pangenome!.pairs[0]!;
  const p3 = results.pangenome!.pairs[1]!;
  return {
    ...done,
    status: 'running',
    partial: true,
    progress: { done: 2, total: 5, stage: 'pangenome', running: ['sorghum_grassl'] },
    finished_at: null,
    results: {
      ...results,
      specificity: { target: 'genome', pairs: [results.specificity!.pairs[0]!] },
      pangenome: {
        target: 'genome',
        pairs: [
          { ...p2, genomes: [p2.genomes[0]!], summary: { genomes_total: 1, single_perfect: 1, single_mismatch: 0, multiple: 0, no_amplicon: 0, db_unavailable: 0, error: 0, amplifies: 1 } },
          { ...p3, genomes: [], summary: { genomes_total: 0, single_perfect: 0, single_mismatch: 0, multiple: 0, no_amplicon: 0, db_unavailable: 0, error: 0, amplifies: 0 } },
        ],
      },
    },
  };
}

/** Transcript design on SORBI_3004G087700.3 with the verified J_L + P1_R pair (real cDNA template). */
export function transcript87700Design(): DesignResponse {
  const f = designFixture('transcript-SORBI_3004G087700.3').response;
  return { ...f, pairs: [qpcrCheckPair] };
}
