// Public React components (spec §C.2).
export { PrimerDesigner, designRequestFor } from './PrimerDesigner';
export { PairsTable, type PairsTableProps } from './PairsTable';
export { SetsTable, type SetsTableProps } from './SetsTable';
export { AssayOptions, type AssayOptionsProps } from './AssayOptions';
export { AlleleMatrix, type AlleleMatrixProps } from './AlleleMatrix';
export { ManualVariantInputs, type ManualVariantInputsProps, type ManualVariant } from './ManualVariantInputs';
export { VariantPicker, type VariantPickerProps } from './VariantPicker';
export { VariantBrowser, type VariantBrowserProps } from './VariantBrowser';
export { OrientationExplain, type OrientationExplainProps } from './OrientationExplain';
export { OrderSheet, type OrderSheetProps } from './OrderSheet';
export { GenotypingPanel, type GenotypingPanelProps } from './GenotypingPanel';
export { SetDetail, type SetDetailProps } from './SetDetail';
export { AgreementMark, AlleleChip, AlleleLegend, GenotypeChip, PredictionChip, PrimerStatusChip, type GenotypeChipProps } from './GenotypeChip';
export { TemplateMap, packPairLanes, niceTicks, type TemplateMapProps, type MapSite } from './TemplateMap';
export { DigestPanel, siteWithCut, type DigestPanelProps } from './DigestPanel';
export { SpecificityResults, type SpecificityResultsProps } from './SpecificityResults';
export { PangenomeMatrix, PangenomeLegend, buildMatrixRows, type PangenomeMatrixProps, type MatrixRow, type MatrixCell } from './PangenomeMatrix';
export { GenomePicker, genomeAvailability, type GenomePickerProps } from './GenomePicker';
export { MASK_SOURCE_LABELS, expectedMaskSource } from './RepeatOptions';
export { VERDICT_META, type VerdictChipValue } from './VerdictChip';
export { WARNING_TEXT } from './Warnings';
export { designerReducer, type DesignerAction } from './reducer';
export type { StyleProps, Theme } from './Root';
